name: Docker image build
on:
  workflow_call:
    inputs:
      image:
        type: string
        default: quay.io/pypa/manylinux2014_x86_64
      plat:
        type: string
        default: manylinux2014_x86_64
      pre_cmd:
        type: string
        default:
      cuda_compiler_version:
        type: string
        default: None
      name:
        type: string
        default: cpu
      options:
        type: string
        default: -DENABLE_CUDA=off

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Free space
        run: |
          sudo rm -rf /usr/local/lib/android/sdk /opt/hostedtoolcache /usr/share/swift /opt/az

      - name: Set env context
        run: |
          echo RUN_STAMP=docker-${{ runner.os }}-${{ inputs.name }} >>$GITHUB_ENV

      - name: Pull image
        run: |
          docker pull ${{ inputs.image }}

      - name: Build wheels
        run: |
          docker run --rm -e PLAT=${{ inputs.plat }} -v `pwd`:/io ${{ inputs.image }} ${{ inputs.pre_cmd }} /io/scripts/build-wheels.sh
          ls wheelhouse/
     
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.RUN_STAMP }}-wheels
          path: wheelhouse

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.RUN_STAMP }}-logs
          path: |
            build/*.log
            build/CMakeCache.txt 
            build/CMakeFiles/*.log

